Scoreboard UI
rkuenzi-epfl/Wnder pull request #162
Opened 2021-05-10 08:51 UTC by JeremyDezalos

2021-05-10 09:38 UTC, rkuenzi-epfl requested changes
There's some lint warning but otherwise it's great.
Also I think we can find a better button, maybe a floating action button with a <- that we could put on the bottom right over the scoreboard.
The scores could also use some improvement, maybe a slightly bigger text for the values and eventually write the place on the left.

2021-05-10 09:38 UTC, rkuenzi-epfl commented on app/src/main/res/layout/scoreboard_entry.xml
> +            android:text="username"
Lint warning:
"Hardcoded string "username", should use `@string` resource"

2021-05-10 09:38 UTC, rkuenzi-epfl commented on app/src/main/res/layout/activity_scoreboard.xml
> +            android:layout_height="match_parent"/>
Lint warning:
"This androidx.recyclerview.widget.RecyclerView should use `android:layout_height="wrap_content"`"
It seems he is unhappy that you use "match_parent" but I guess the result will look a bit different if you change it?

2021-05-10 09:57 UTC, JeremyDezalos reviewed
Definitely the best way to answer comments

2021-05-10 09:57 UTC, JeremyDezalos commented on app/src/main/java/com/github/wnder/ScoreboardActivity.java
>  import android.widget.TableLayout;
Done

2021-05-11 09:10 UTC, rkuenzi-epfl approved these changes

2021-05-12 14:04 UTC, amattei777 approved these changes
Didn't find any major problem. We will discuss to uniformize the details that are left for the design during the last stand up meeting I believe

2021-05-12 14:04 UTC, amattei777 commented on app/src/main/res/layout/activity_scoreboard.xml
> +        app:srcCompat="@drawable/ic_baseline_arrow_back_24"
We will have one day to discuss with the team to decide on some guidelines for the typical margins/colors to use in the app so we use all the same. We will do that later apparently thought.

2021-05-12 14:13 UTC, amattei777 approved these changes

2021-05-12 16:10 UTC, merged