implemented basic fragment for radius bar
rkuenzi-epfl/Wnder pull request #168
Opened 2021-05-12 16:36 UTC by JeremyDezalos

2021-05-12 17:10 UTC, JeremyDezalos commented
Dear all,

Please ignore code climate duplication problem, those will be resolved when we delete MainActivity.

Thank you.

Have a good day.

Jeremy Dezalos

2021-05-12 22:44 UTC, rkuenzi-epfl requested changes
Some lints as always and something you can simplify in test.

2021-05-12 22:44 UTC, rkuenzi-epfl commented on app/src/androidTest/java/com/github/wnder/NavigationActivityTest.java
> +        onView(withId(R.id.navigationToGuessButton)).perform(ViewActions.click());
ViewActions.click() is statically imported yo you can simply use click

2021-05-12 22:44 UTC, rkuenzi-epfl commented on app/src/main/res/layout/fragment_seekbar.xml
> +    <com.google.android.material.floatingactionbutton.FloatingActionButton
Lint warning "Missing `contentDescription` attribute on image"

2021-05-12 22:44 UTC, rkuenzi-epfl commented on app/src/main/res/layout/fragment_seekbar.xml
> +        android:clickable="true"
Lint warning "'clickable' attribute found, please also add 'focusable'"

2021-05-13 10:35 UTC, rkuenzi-epfl approved these changes

2021-05-13 11:05 UTC, leonardvaney requested changes
There is a sick bar, I can move it, click on the button and go to the next activity. The radius in the global user is modified in the listener so it should be working exactly like before.
I just have these two comments + some of the classes have too many unused import and the javadoc is inequal (but don't worry too much about the javadoc).

2021-05-13 13:11 UTC, leonardvaney approved these changes

2021-05-13 13:35 UTC, merged