Display camera preview directly in TakePictureFragment
rkuenzi-epfl/Wnder pull request #200
Opened 2021-05-19 23:51 UTC by stblr

2021-05-26 13:56 UTC, rkuenzi-epfl requested changes
You should add some Javadoc to your function and add few comments in general because I really think what you do won't seem obvious to the others that will have to work on this soon. 
Otherwise it's ok.
For the tests I guess we will have to do without them on cirrus, but please leave them as comment so that if we think we broke something with your code we can at least test it locally.

2021-05-26 13:56 UTC, rkuenzi-epfl commented on app/src/main/java/com/github/wnder/TakePictureFragment.java
> +
This could probably go in the else statement right before launching?

2021-05-27 23:49 UTC, rkuenzi-epfl approved these changes
For me it's ok, but the bug on cirrus is even weirder than expected I think?
I though the camera couldn't be opened on cirrus but from the test you committed here it seems there is no issues with the camera opening but it prevents you from using the buttons once it's opened which is really strange. So I guess we will have to do with these partial tests.

2021-05-28 07:58 UTC, amattei777 approved these changes
LGFM

2021-05-28 07:59 UTC, merged