Add tour activity
rkuenzi-epfl/Wnder pull request #228
Opened 2021-05-27 16:50 UTC by stblr

2021-05-28 09:20 UTC, amattei777 requested changes
Add call to GuessLocationTourMode that will be merged soon and it will be ok.

2021-05-28 09:20 UTC, amattei777 commented on app/src/main/res/layout/tour_entry.xml
> +        <ImageView
the contentDescription warnings on images are there

2021-06-04 16:33 UTC, leonardvaney requested changes
The PR is not linked with the GuessLocationActivity at the moment where I'm doing this review, so I'm waiting this to approve.

2021-06-04 16:33 UTC, leonardvaney commented on app/src/androidTest/java/com/github/wnder/TourActivityTest.java
> +        onView(withText("52 km")).check(matches(isDisplayed()));*/
I guess it is no working? If so, you can remove it, but it doesn't seem to be wrong...

2021-06-04 16:33 UTC, leonardvaney commented on app/src/main/java/com/github/wnder/tour/TourAdapter.java
> +        });
There is a code climate issue that you can easily remove here.

2021-06-04 16:33 UTC, leonardvaney commented on app/src/main/java/com/github/wnder/user/FirebaseUserDatabase.java
> +            // Keep the 10 closest tours
The comment is not correct anymore.

2021-06-04 19:24 UTC, amattei777 approved these changes

2021-06-04 19:24 UTC, leonardvaney approved these changes

2021-06-04 19:24 UTC, merged