Feature/picture location
rkuenzi-epfl/Wnder pull request #57
Opened 2021-03-25 23:40 UTC by stblr

2021-04-12 14:38 UTC, JeremyDezalos commented
The android checks seem to fail

2021-04-14 13:32 UTC, leonardvaney commented on app/src/androidTest/java/com/github/wnder/ExistingPictureTesting.java
>      public static void getTestPic(){
Is it necessary to be static?

2021-04-14 13:33 UTC, leonardvaney approved these changes
Sorry, it was supposed to be approved.

2021-04-15 13:26 UTC, JeremyDezalos approved these changes

2021-04-15 13:26 UTC, JeremyDezalos commented on app/src/main/java/com/github/wnder/picture/ExistingPicture.java
> +            double radius = 200; // meters
Wouldn't it be better to pass this as argument because at some point we would like to tune the difficulty ?

2021-04-15 13:27 UTC, JeremyDezalos requested changes
The tests crash

2021-04-16 07:26 UTC, amattei777 approved these changes
Approval for the changes done for Jeremy requests

2021-04-16 07:28 UTC, merged