Feature/close pictures
rkuenzi-epfl/Wnder pull request #91
Opened 2021-04-12 08:32 UTC by BoostedBoat

This features lets a user decide a radius in which the next selected pictures will be chosen

2021-04-12 14:20 UTC, rkuenzi-epfl requested changes
Use lambdas!

2021-04-12 14:20 UTC, rkuenzi-epfl commented on app/src/main/java/com/github/wnder/user/User.java
> +            Resources resources;
Is this line ever used?

2021-04-12 14:20 UTC, rkuenzi-epfl commented on app/src/main/java/com/github/wnder/Storage.java
> +        });
Use lambdas

2021-04-15 14:14 UTC, BoostedBoat commented on app/src/main/java/com/github/wnder/user/User.java
> +            Resources resources;
removed and never to be seen again

2021-04-15 14:14 UTC, BoostedBoat commented on app/src/main/java/com/github/wnder/Storage.java
> +        });
tried to do something

2021-04-15 17:38 UTC, rkuenzi-epfl approved these changes

2021-04-15 19:21 UTC, merged