skipped pics lose 1 karma + you can get karma of a pic
rkuenzi-epfl/Wnder pull request #96
Opened 2021-04-15 13:39 UTC by BoostedBoat

!!! Don't merge while PR 90 has not been merged, in need of refractoring !!!

2021-04-26 10:56 UTC, leonardvaney commented
Can you modifiy the xml file of GuessPreviewActivity to remove the cirrus errors?

2021-04-26 15:24 UTC, JeremyDezalos approved these changes
Remove the commented function otherwise it's fine

2021-04-27 08:45 UTC, BoostedBoat commented on app/src/androidTest/java/com/github/wnder/GuessPreviewActivityTest.java
> +
Deleted

2021-04-27 08:59 UTC, stblr requested changes

2021-04-27 08:59 UTC, stblr commented on app/src/main/java/com/github/wnder/GuessPreviewActivity.java
> +import com.github.wnder.picture.ExistingPicture;
Duplicate

2021-04-27 08:59 UTC, stblr commented on app/src/main/java/com/github/wnder/GuessPreviewActivity.java
>  import androidx.appcompat.app.AppCompatActivity;
Duplicate

2021-04-27 09:58 UTC, stblr approved these changes

2021-04-27 10:14 UTC, merged